# (Reads environment configuration dynamically from local .env via Secret)

# PERSISTENT VOLUME CLAIM & INITIALIZATION CONFIGMAP FOR POSTGRESQL
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
# Request 2gb of persistent disk sotrage from cluster. prevents database loss when postgresql pods restart.
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init-sql
data:
  init_pr.sql: |
    CREATE TABLE IF NOT EXISTS trips (
        trip_id VARCHAR(36) PRIMARY KEY,
        timestamp TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
        origin VARCHAR(255) NOT NULL,
        destination VARCHAR(255) NOT NULL,
        geometry_polyline TEXT NOT NULL,
        origin_coords VARCHAR(100) NOT NULL,
        dest_coords VARCHAR(100) NOT NULL,
        vehicle_type VARCHAR(50) NOT NULL,
        cargo_weight_kg DECIMAL(10, 2) NOT NULL,
        route_priority VARCHAR(50) DEFAULT 'green',
        recommended_route_id VARCHAR(50) NOT NULL,
        predicted_co2_kgco2e DECIMAL(12, 4),
        distance_km DECIMAL(10, 2),
        duration_minutes DECIMAL(10, 2)
    );

# Stores the SQL intilisation schema script.
# It's mounted into /docker-entrypoint-initdb.d/init_pr.sql so that the PostgreSQL container automatically executes it on startup, creating the trips table automatically on the first activation.
---

# POSTGRESQL DATABASE (DEPLOYMENT & SERVICE)

apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-db
  template:
    metadata:
      labels:
        app: postgres-db
    spec:
      containers:
        - name: postgres
          image: postgres:15-alpine
          envFrom:
            - secretRef:
                name: logistics-secret
          ports:
            - containerPort: 5432
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgres-data-volume
            - mountPath: /docker-entrypoint-initdb.d/init_pr.sql
              subPath: init_pr.sql
              name: postgres-init-volume
      volumes:
        - name: postgres-data-volume
          persistentVolumeClaim:
            claimName: postgres-pvc
        - name: postgres-init-volume
          configMap:
            name: postgres-init-sql
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-db
spec:
  selector:
    app: postgres-db
  ports:
    - port: 5432
      targetPort: 5432
  type: ClusterIP


# ClusterIP keeps the database service internal to the Kubernetes cluster, for security so the database is not exposed
---

# DATABASE REST API SERVICE (DEPLOYMENT & SERVICE)

apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db-service
  template:
    metadata:
      labels:
        app: db-service
    spec:
      containers:
        - name: db-service
          image: db-service:v2
          imagePullPolicy: IfNotPresent
          envFrom:
            - secretRef:
                name: logistics-secret
          ports:
            - containerPort: 8002
# The database service is a REST API that provides an interface for the frontend and other services to interact with the PostgreSQL database. It handles requests for storing and retrieving trip data, ensuring that the data is managed securely and efficiently.
---
apiVersion: v1
kind: Service
metadata:
  name: db-service
spec:
  selector:
    app: db-service
  ports:
    - port: 8002
      targetPort: 8002
  type: LoadBalancer

# The LoadBalancer service type exposes the database service externally, allowing other services and the frontend to access it. 
# It provides a stable IP address for external access, making it easier to connect to the database service from outside the Kubernetes cluster.
---

# ML PREDICTION SERVICE (DEPLOYMENT & SERVICE)

apiVersion: apps/v1
kind: Deployment
metadata:
  name: ml-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ml-service
  template:
    metadata:
      labels:
        app: ml-service
    spec:
      containers:
        - name: ml-service
          image: ml-service:v2
          imagePullPolicy: IfNotPresent
          envFrom:
            - secretRef:
                name: logistics-secret
          ports:
            - containerPort: 8000

# Lets the ML service be accessed internally by other services within the Kubernetes cluster, such as the routing engine and database service, without exposing it to external traffic.

---
apiVersion: v1
kind: Service
metadata:
  name: ml-service
spec:
  selector:
    app: ml-service
  ports:
    - port: 8000
      targetPort: 8000
  type: ClusterIP

# configured clusterip on port 8000
---
# ROUTING ENGINE (DEPLOYMENT & SERVICE)

apiVersion: apps/v1
kind: Deployment
metadata:
  name: routing-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: routing-service
  template:
    metadata:
      labels:
        app: routing-service
    spec:
      containers:
        - name: routing-service
          image: routing-service:v2
          imagePullPolicy: IfNotPresent
          envFrom:
            - secretRef:
                name: logistics-secret
          ports:
            - containerPort: 8001
---
apiVersion: v1
kind: Service
metadata:
  name: routing-service
spec:
  selector:
    app: routing-service
  ports:
    - port: 8001
      targetPort: 8001
  type: LoadBalancer

# Loadbalancer on port 8001 to also allow external access to the routing engine service, enabling the frontend and other services to request route optimizations and interact with the routing engine.

# It passes ML_SERVICE_URL and OSRM_SERVICE_URL as environment variables to the routing engine, allowing it to communicate with the ML prediction service and the OSRM routing service.

---
# FRONTEND UI (DEPLOYMENT & SERVICE)=


apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-ui
  template:
    metadata:
      labels:
        app: frontend-ui
    spec:
      containers:
        - name: frontend-ui
          image: frontend-ui:v5
          imagePullPolicy: IfNotPresent
          envFrom:
            - secretRef:
                name: logistics-secret
          ports:
            - containerPort: 80


---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: frontend-ui
  ports:
    - port: 3000
      targetPort: 80
  type: LoadBalancer

# Ensures that the frontend UI is accessible externally, allowing users to interact with the application through a web interface. 
# Configured as LoadBalancer on port 3000 (so it can be accessed via localhost:3000 or the ip provided by the cluster).

